# Travis file upgraded to stack at 2015-31-12 using template from
# <http://docs.haskellstack.org/en/stable/travis_ci.html>.
#
# Travis file initially created at 2015-05-31 using template from
# <https://github.com/hvr/multi-ghc-travis/commit/c9c87d36c450d7f9cb3183dcaf1f77b60f916f28>
# and taking the idea of using cabal-meta from yesodweb/yesod.

sudo: false

services:
 - redis-server

addons:
 postgresql: "9.3"

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: STACKARGS="--flag serversession-backend-redis:old-locale --stack-yaml=stack_lts-2.yaml"
    - env: STACKARGS="--resolver=lts-3"
    - env: STACKARGS="--resolver=lts-4"
    - env: STACKARGS="--resolver=lts-5"
    - env: STACKARGS="--resolver=lts-6"
    - env: STACKARGS="--resolver=lts-7"
    - env: STACKARGS="--stack-yaml=stack_lts-7.yaml"
    - env: STACKARGS="--stack-yaml=stack_nightly.yaml"
  allow_failures:
    - env: STACKARGS="--stack-yaml=stack_nightly.yaml"

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres

install:
  - stack setup $STACKARGS

script:
  - stack test $STACKARGS serversession
  - stack test $STACKARGS serversession-backend-acid-state
  - du -hcs serversession-backend-acid-state/state; rm -Rfv serversession-backend-acid-state/state
  - stack test $STACKARGS serversession-backend-persistent --test-arguments='"--skip=100 MiB"'
  - du -hcs serversession-backend-persistent/test.db*; rm -Rfv serversession-backend-persistent/test.db*
  - psql -c 'SELECT COUNT(*) FROM "persistent_session";' -U test test; psql -c 'DROP DATABASE test;' -U postgres
  - stack test $STACKARGS serversession-backend-redis
  - redis-cli FLUSHALL
  - stack test $STACKARGS --no-run-tests # Make sure everything else builds
  - stack $STACKARGS sdist
