resolver: lts-10.3
packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-snap
  - serversession-frontend-wai
  - serversession-frontend-yesod
  - examples/serversession-example-yesod-persistent
flags:
  serversession:
    lib-Werror: true
  serversession-backend-acid-state:
    lib-Werror: true
  serversession-backend-persistent:
    lib-Werror: true
  serversession-backend-redis:
    lib-Werror: true
  serversession-frontend-snap:
    lib-Werror: true
  serversession-frontend-wai:
    lib-Werror: true
  serversession-frontend-yesod:
    lib-Werror: true
extra-deps:
  # for lts 9, 10
  - acid-state-0.14.3
  - snap-1.1.0.0
  - snap-core-1.0.3.1
  - snap-server-1.0.3.3
  - heist-1.0.1.2
  - map-syntax-0.2.0.2
  - xmlhtml-0.2.5.2
  # for lts-8
  - blaze-html-0.9.0.1
  - blaze-markup-0.8.2.0
